### ISSUE TITLE
Serializers to sort collections

### ISSUE THREAD

**Issue by sschuberth** [Kantis/ks3#112]
In serialized formats, it's often nice for a better overview to have collection entries sorted naturally / alphabetically / by some comparator. So what do you guys think about adding convenience serializers to do that?

**Comment by Kantis** [comment]
I'm not sure if it would be more convenient than simply sorting your data before serializing. I guess for bigger structures it could be?

How do you propose it would work?

**Comment by sschuberth** [comment]
> I guess for bigger structures it could be?

Yes, and for immutable data class hierarchies you don't want to create copies just to sort a deeply nested collection for serialization. In memory, the order does not matter. This is just for readability and canonization in the serialized format.

> How do you propose it would work?

Similar to [these](https://github.com/oss-review-toolkit/ort/blob/d14c144283f840e057d422ca0587b12e449abffa/plugins/reporters/gitlab/src/main/kotlin/GitLabLicenseModel.kt#L105-L122), but more generically implemented.

**Comment by Kantis** [comment]
Okay,  sure! Would you like to contribute it?

**Comment by sschuberth** [comment]
Maybe, yes, eventually 😀 I doesn't have high priority for me currently, though.
