### ISSUE TITLE
Consider changing the `typealias` package name

### ISSUE THREAD

**Issue by sschuberth** [Kantis/ks3#113]
As noted over [here](https://github.com/oss-review-toolkit/ort/pull/8332#discussion_r1500590235), the need to escape the `typealias` package name due to the reserved keyword is a bit ugly, despite the IDE adding it automatically. Maybe just rename it to plural "typealiases"?

**Comment by Kantis** [comment]
I agree we should do it. It has bothered me a bit too. Thanks for raising the issue 👍🏼 I think it can be done whilst keeping the old package in place, and we can remove old package when we go for 1.0
