### ISSUE TITLE
Cannot run JVM tests from IDE

### ISSUE THREAD

**Issue by sschuberth** [Kantis/ks3#118]
Running Kotest from the IDE does not work for me by pressing the green button from the gutter of a test class. E.g. for `ByteArrayAsBase64StringSerializerTest` I just get "No JDK specified". From other KMP projects I'm used to see a nested menu popping up, allowing me to choose the platform I want to run tests for.

**Comment by Kantis** [comment]
Had that issue as well. I'll poke around a bit.

**Comment by Kantis** [comment]
Downgrading to IntelliJ 2023.2 seems to help for me. ☹️
