### ISSUE TITLE
Publishing of version 0.6.0 did not seem to work

### ISSUE THREAD

**Issue by sschuberth** [Kantis/ks3#123]
The artifacts do not seem to be available yet anywhere, could you please check @Kantis?

**Comment by sschuberth** [comment]
Now it seems to be there 👍🏻 See e.g. https://github.com/oss-review-toolkit/ort/pull/8416.

**Comment by Kantis** [comment]
@sschuberth publishing got cancelled when I committed the readme update, then I got busy with other things . Thanks for raising the issue 👍
