### ISSUE TITLE
windows (mingwX64Test) failure: ModuleVersionNotFoundException: Could not find :kotlin-native-prebuilt-windows-x86_64:1.7.2

### ISSUE THREAD

**Issue by aSemy** [Kantis/ks3#25]
I'm not sure why this workflow is failing - it looks okay

https://github.com/Kantis/ks3/actions/runs/3330228810/jobs/5508472601#step:6:265

https://github.com/Kantis/ks3/actions/runs/3330228810/jobs/5508472601#step:6:542

Might be related to the centralised repo definitions, or perhaps Gradle is timing out when downloading the large file?

**Comment by Kantis** [comment]
I think the centralised repo definitions is most likely candidate. Timeout shouldn't happen when an active transfer is in progress

**Comment by aSemy** [comment]
It's strange because I think the centralised repos have worked before...

https://github.com/Kantis/ks3/actions/runs/3316468369/jobs/5478306674
