### ISSUE TITLE
Name the thing

### ISSUE THREAD

**Issue by Kantis** [Kantis/ks3#3]
Do you think `ks3` is fine? `k3s`? I was thinking KS3 for **K**otlinX **S**erialization **S**tandard **S**erializers -> KSSS -> KS3

**Comment by aSemy** [comment]
I like it because it's short, but I first got confused because I misread it as k3s, which is already a thing

**Comment by Kantis** [comment]
Ah.. right. I think most people interested in the one don't care too much about the other, so I don't really mind the similarity.

**Comment by Kantis** [comment]
Registered the domain now :)

**Comment by aSemy** [comment]
Nice one! The name has grown on me
