### ISSUE TITLE
ByteArray as base64 string

### ISSUE THREAD

**Issue by aSemy** [Kantis/ks3#7]
Provide a serializer that encodes/decodes a [`ByteArray`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-byte-array/) as a base64 encoded String

See

* https://github.com/Kotlin/kotlinx.serialization/pull/1676
* https://github.com/Kotlin/kotlinx.serialization/issues/1633
* https://stackoverflow.com/questions/74049511/parse-a-byte-array-into-a-bytearray

Considerations:

* `ByteArray` is multiplatform, so the implementation will either need to be pure Kotlin, or have platform specific implementations. Perhaps use https://square.github.io/okio/?
* Should we also provide other encodings, like base16, base32, base64, base85?

**Comment by Kantis** [comment]
> Should we also provide other encodings, like base16, base32, base85?

I think we can hold off on that until someone makes a compelling argument for adding them.

> ByteArray is multiplatform, so the implementation will either need to be pure Kotlin, or have platform specific implementations. Perhaps use https://square.github.io/okio/?

I think we can use the implementation from `https://github.com/square/okio/blob/master/okio/src/commonMain/kotlin/okio/-Base64.kt`, as long as we keep attribution to the original author, right? I would prefer not to pull the entire okio lib in just for base64 encoding at the moment.
