### ISSUE TITLE
`ListSerializer` that ignores invalid elements

### ISSUE THREAD

**Issue by aSemy** [Kantis/ks3#9]
https://github.com/Kotlin/kotlinx.serialization/issues/1205

> **What is your use-case and why do you need this feature?** I'm receiving a list of items from the server. Some of the items might miss some required fields or be otherwise malformed. In this case, I would like to ignore the items that failed to parse but still parse the ones that I can. Unfortunately, it looks like `ListSerializer` is failing as soon as it encounters a single list item which it fails to parse.
> 
> **Describe the solution you'd like** Some sort of `ignoreFailedListItems` or `allowPartialListResults` configuration.
> 
> *This probably applies to all collections.

**Comment by Kantis** [comment]
I can't really figure out any good ways to implement this. The tricky part is figuring out how to discard and move the decoder forward. The Decoder delegates responbility of consuming a single item to us.. and we don't really know how to skip the "invalid" data and move along to next possibly valid entry.

With JSON it's possible to handle some scenarios using `JsonDecoder.decodeJsonElement` but it doesn't even cover all cases in JSON world (I managed to make it fail by throwing in an object with an invalid key in the list)

```kotlin
@OptIn(InternalSerializationApi::class)
inline fun <reified T : Any> listSerializerIgnoringInvalidItems(
   itemSerializer: KSerializer<T>? = null,
): KSerializer<List<T>> =
   object : KSerializer<List<T>> {

      private val actualItemSerializer = itemSerializer ?: T::class.serializer()
      private val listSerializer = ListSerializer(actualItemSerializer)

      override val descriptor = listSerializer.descriptor

      override fun deserialize(decoder: Decoder): List<T> {
         return decoder.beginStructure(descriptor).run {
            buildList {
               while (true) {
                  val index = decodeElementIndex(descriptor)
                  if (index == CompositeDecoder.DECODE_DONE) break
                  try {
                     add(decodeSerializableElement(descriptor, index, actualItemSerializer))
                  } catch (e: Exception) {
                     // TODO: Discard the item so next list item appears
                  }
               }
               endStructure(descriptor)
            }
         }
      }

      override fun serialize(encoder: Encoder, value: List<T>) {
         listSerializer.serialize(encoder, value)
      }
   }

```
